name: Update README

on:
  schedule:
    - cron: '35 0 5 1 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: danielgros/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            GH_USERNAME: danielgros
            COMMIT_NAME: GitHub Activity Digest
            COMMIT_MSG: "Update GitHub Activity in README.md"
            MAX_LINES: 10
            TARGET_FILE: README.md
